### ISSUE TITLE
Summarizing duplicate notifications

### ISSUE THREAD

**Issue by DarkWolf7** [stuckless/sagex.plugin.pushbullet#1]
In some cases (such as when a tuner stops working), SageTV will send several messages of the event as long as it is going on. These are basically duplicates and it would be far preferable to either discard or summarize them. The SageTV UI already does this to an extent. An example might be:

"Tuner has stopped working (5x)"

**Comment by stuckless** [comment]
I'm going to close this out, since I did add the max message count.  This is also a good idea, but, in order to do this I'd have to delay sending the messages and store them, until I decided that there were no more and then send the message.  This is a lot of work for a simple plugin like this, that really just behaves as a message forwarding system.  Hopefully the Max Repeat will suffice.  The UI can do this, because the UI is just reading the message and display the repeat count, but, as forwarding system, this is more challenging.
